# Analisis de tiempo

El tiempo que se demora un programa en resolver un problema
Un problema clásico (como el sort) es aquel que existe desde tiempos immemoriables.
Hay métodos de selección, búsqueda algorítmica en grafos, programación lineal, etc.

Los algoritmos se conciben con esquemas, patrones de diseño, divide y vencerás, probramación dinámica, algoritmos greedy (una solución rápida pero no la mejor), etc.

### Un algoritmo va a ser eficaz si se comporta de manera razonable independientemente de la plataforma incluso para datos de gran tamaño

##### Complejidad en el mejor caso
##### Complejidad en el peor caso
##### Complejidad en caso medio: hace falta una distribución de probabilidades para todo dato de entrada n

### Generar un arreglo de tamaño n de elementos aleatorios de 1 a 100

In [7]:
import numpy as np
def genrandarray(n):
    array = []
    for i in range(n):
        array.append(np.random.randint(1,101))
    print(array)
    return array

In [8]:
array = genrandarray(50)

[1, 11, 78, 81, 40, 18, 96, 77, 91, 78, 91, 11, 12, 71, 70, 57, 70, 95, 64, 17, 50, 87, 24, 28, 86, 75, 57, 68, 32, 42, 90, 18, 9, 2, 18, 78, 91, 100, 33, 77, 60, 20, 79, 35, 11, 70, 54, 49, 51, 3]


### Imprimir datos del arreglo

In [9]:
for i in range(len(array)):
    print(array[i], end= " - ")

1 - 11 - 78 - 81 - 40 - 18 - 96 - 77 - 91 - 78 - 91 - 11 - 12 - 71 - 70 - 57 - 70 - 95 - 64 - 17 - 50 - 87 - 24 - 28 - 86 - 75 - 57 - 68 - 32 - 42 - 90 - 18 - 9 - 2 - 18 - 78 - 91 - 100 - 33 - 77 - 60 - 20 - 79 - 35 - 11 - 70 - 54 - 49 - 51 - 3 - 

### Dar reversa a un arreglo de dos formas

In [10]:
#Forma 1
def reversa(arreglo):
    n = len(a)
    for i in range(n//2):
        temp = a[i]
        a[i] = a[n-1-i]
        a[n-1-i] = t

#Forma 2
#array.reverse()
for i in array :
    print(i, end= " - ")

1 - 11 - 78 - 81 - 40 - 18 - 96 - 77 - 91 - 78 - 91 - 11 - 12 - 71 - 70 - 57 - 70 - 95 - 64 - 17 - 50 - 87 - 24 - 28 - 86 - 75 - 57 - 68 - 32 - 42 - 90 - 18 - 9 - 2 - 18 - 78 - 91 - 100 - 33 - 77 - 60 - 20 - 79 - 35 - 11 - 70 - 54 - 49 - 51 - 3 - 

### Minimo valor de un arreglo

In [11]:
min = 102
for num in array:
    if num < min: 
        min = num
        
print(min)

1


### La media del arreglo

In [13]:
def mediaarreglo(a):
    print(sum(a)/len(a))
    
mediaarreglo(array)

52.52


### Las ocurrencias de valores en el arreglo

In [16]:
def ocurrencias(a):
    oc = [0] * (max(a) + 1) #arreglo de tamaño de 0 a 100
    for x in a:
        oc[x] += 1
    return oc
print("Ocurrencias...")
oc = ocurrencias(array)
for i in range(len(oc)):
    if oc[i] > 0:
        print("El valor ", i," ocurre ", oc[i], " veces")

Ocurrencias...
El valor  1  ocurre  1  veces
El valor  2  ocurre  1  veces
El valor  3  ocurre  1  veces
El valor  9  ocurre  1  veces
El valor  11  ocurre  3  veces
El valor  12  ocurre  1  veces
El valor  17  ocurre  1  veces
El valor  18  ocurre  3  veces
El valor  20  ocurre  1  veces
El valor  24  ocurre  1  veces
El valor  28  ocurre  1  veces
El valor  32  ocurre  1  veces
El valor  33  ocurre  1  veces
El valor  35  ocurre  1  veces
El valor  40  ocurre  1  veces
El valor  42  ocurre  1  veces
El valor  49  ocurre  1  veces
El valor  50  ocurre  1  veces
El valor  51  ocurre  1  veces
El valor  54  ocurre  1  veces
El valor  57  ocurre  2  veces
El valor  60  ocurre  1  veces
El valor  64  ocurre  1  veces
El valor  68  ocurre  1  veces
El valor  70  ocurre  3  veces
El valor  71  ocurre  1  veces
El valor  75  ocurre  1  veces
El valor  77  ocurre  2  veces
El valor  78  ocurre  3  veces
El valor  79  ocurre  1  veces
El valor  81  ocurre  1  veces
El valor  86  ocurre  1  vec

### Crear un arreglo de 100 enteros

In [26]:
def ej2a(n):
    return [i for i in range(1,n+1)]
ej2a(100)


[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

### Crear un arreglo de numeros pares

In [24]:
def ej2b(n):
    return [i for i in range(1,n+1) if i%2 == 0]
ej2b(20)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

### Sudoku validando celdas

In [29]:
grid

array([[7, 3, 5, 6, 1, 4, 8, 9, 2],
       [8, 4, 2, 9, 7, 3, 5, 6, 1],
       [9, 6, 1, 2, 8, 5, 3, 7, 4],
       [2, 8, 6, 3, 4, 9, 1, 5, 7],
       [4, 1, 3, 8, 5, 7, 9, 2, 6],
       [5, 7, 9, 1, 2, 6, 4, 3, 8],
       [1, 5, 7, 4, 9, 2, 6, 8, 3],
       [6, 9, 4, 7, 3, 8, 2, 1, 5],
       [3, 2, 8, 5, 6, 1, 7, 4, 9]])

In [25]:
print(grid2)

[[7 8 9 2 4 5 1 6 3]
 [3 4 6 8 1 7 5 9 2]
 [5 2 1 6 3 9 7 4 8]
 [6 9 2 3 8 1 4 7 5]
 [1 7 8 4 5 2 9 3 6]
 [4 3 5 9 7 6 2 8 1]
 [8 5 3 1 9 4 6 2 7]
 [9 6 7 5 2 3 8 1 4]
 [2 1 4 7 6 8 3 5 9]]


In [40]:
#Inicializar el mapa de sudoku
import numpy as np
grid = np.array([[7,3,5,6,1,4,8,9,2],
[8,4,2,9,7,3,5,6,1],
[9,6,1,2,8,5,3,7,4],
[2,8,6,3,4,9,1,5,7],
[4,1,3,8,5,7,9,2,6],
[5,7,9,1,2,6,4,3,8],
[1,5,7,4,9,2,6,8,3],
[6,9,4,7,3,8,2,1,5],
[3,2,8,5,6,1,7,4,9]])

grid2 = gridnp.transpose()

def validarceldas(grid):
    for row in grid:
        temp = [0]*9
        for num in row:
            if(num!=0):
                temp[num-1]+=1
                if(temp[num-1]>1):
                    print("Error en celda horizontal")
                    return
                
    print("celdas horizontales correctas")
    for row in grid.transpose():
        temp = [0]*9
        for num in row:
            if(num!=0):
                temp[num-1]+=1
                if(temp[num-1]>1):
                    print("Error en celda vertical")
                    return
    print("celdas verticales correctas")
    print("La complejidad es n^2")
    return

validarceldas(grid)


    
#Ver como funciona Set()

celdas horizontales correctas
celdas verticales correctas
La complejidad es n^2


### Criba de Eratóstenes

In [87]:
import math
def numprimos(n):
    a= [True for i in range(n)]
    a[0] = False
    a[1] = False
    for i in range(2,int(math.sqrt(n))+1):
        if(a[i]==True):
            for j in range(i*i,n,i):
                a[j] = False
    print([i for i in range(len(a)) if a[i]])
    
numprimos(100)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
